# Generated by Django 6.0.3 on 2026-04-03 10:30

import django.db.models.deletion
import django_couchbase_orm.db.backends.couchbase.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', django_couchbase_orm.db.backends.couchbase.fields.CouchbaseAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'breweries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', django_couchbase_orm.db.backends.couchbase.fields.CouchbaseAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abv', models.FloatField(blank=True, null=True, verbose_name='ABV %')),
                ('ibu', models.IntegerField(blank=True, null=True, verbose_name='IBU')),
                ('style', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('avg_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.brewery')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
