# Generated by Django 6.0.3 on 2026-04-03 17:49

import django.core.validators
import django.db.models.deletion
import django_couchbase_orm.db.backends.couchbase.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='doc_type',
            field=models.CharField(default='beer', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='brewery',
            name='doc_type',
            field=models.CharField(default='brewery', editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', django_couchbase_orm.db.backends.couchbase.fields.CouchbaseAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='rating', editable=False, max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='beers.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('beer', 'user')},
            },
        ),
    ]
