# Generated by Django 6.0.3 on 2026-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_title',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
